//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easyBilling.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;AttachDbFilename=|DataDirectory|\\Data\\eBilling_DB.mdf;In" +
            "tegrated Security=True")]
        public string eBilling_DBConnectionString {
            get {
                return ((string)(this["eBilling_DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sqlexpress;Initial Catalog=\"J:\\PROJECTS\\MY PROJECTS\\CLIENT PROJECT\\" +
            "EASYBILLING\\EASYBILLING\\EASYBILLING\\BIN\\DEBUG\\DATA\\EBILLING_DB.MDF\";Integrated S" +
            "ecurity=True")]
        public string J__PROJECTS_MY_PROJECTS_CLIENT_PROJECT_EASYBILLING_EASYBILLING_EASYBILLING_BIN_DEBUG_DATA_EBILLING_DB_MDFConnectionStrin {
            get {
                return ((string)(this["J__PROJECTS_MY_PROJECTS_CLIENT_PROJECT_EASYBILLING_EASYBILLING_EASYBILLING_BIN_DE" +
                    "BUG_DATA_EBILLING_DB_MDFConnectionStrin"]));
            }
        }
    }
}
